<a href="https://colab.research.google.com/github/brhmkhn4/python_ka_chilla_0.1/blob/main/Python_ka_chilla_1_0_Lec_15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#1d array

a = np.array([5,5,5,5])
a


array([5, 5, 5, 5])

In [ ]:
#2d array

import numpy as np

b = np.array([[1,1,1,1], [2,2,2,2], [3,3,3,3]])
b

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [ ]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [ ]:
b = np.ones(3)
b

array([1., 1., 1.])

In [ ]:
c = np.empty(3)
c

array([1., 1., 1.])

In [ ]:
e = np.arange(7)
e

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
f = np.arange(3,23)
f

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22])

In [ ]:
h = np.linspace(0,16,num=3)
h

array([ 0.,  8., 16.])

In [ ]:
# making 3d array

d =  np.arange(24).reshape(2,3,4)
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

# Creating an Array using Numpy

In [ ]:
import numpy as np

food = np.array(["item1", "item2", "item3"])
food

array(['item1', 'item2', 'item3'], dtype='<U5')

In [ ]:
price = np.array([5, 5, 5])
price

array([5, 5, 5])

In [ ]:
len(food)

3

In [ ]:
food[0:3]

array(['item1', 'item2', 'item3'], dtype='<U5')

# Heading1
## Heading2
### Heading3
